# Generated by Django 4.2.4 on 2023-08-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=None, upload_to='movie/images/'),
            preserve_default=False,
        ),
    ]
